#!/usr/bin/env bash

set -e

CONFIG_DIR=$1

if [[ -z $CONFIG_DIR ]]
then
  echo "Usage: setup_syslog_forwarder [config dir]"
  exit 1
fi

cp "$CONFIG_DIR/syslog_forwarder.conf" /etc/rsyslog.d/40-helmsman_syslog_forwarder.conf
