#!/usr/bin/env bash

BOSH_CLIENT="$(bosh int "$SOURCE" --path=/client)"
BOSH_CLIENT_SECRET="$(bosh int "$SOURCE" --path=/client_secret)"
BOSH_CA_CERT="$(bosh int "$SOURCE" --path=/ca_cert)"
BOSH_ENVIRONMENT="$(bosh int "$SOURCE" --path=/target)"
if bosh int --path=/jumpbox_ssh_key  "$SOURCE" &>/dev/null ; then
    jumpbox_ssh_key="$(mktemp)"
    bosh int --path=/jumpbox_ssh_key "$SOURCE" > ${jumpbox_ssh_key}
    proxy="ssh+socks5://jumpbox@$(bosh int --path=/jumpbox_url "$1")?private-key=${jumpbox_ssh_key}"
    export BOSH_ALL_PROXY="${proxy}"
fi

export BOSH_CA_CERT BOSH_CLIENT BOSH_CLIENT_SECRET BOSH_ENVIRONMENT

