- type: replace
  path: /instance_groups/name=master/jobs/name=cloud-provider/properties/cloud-config/useManagedIdentityExtension
  value: false

- type: replace
  path: /instance_groups/name=master/jobs/name=cloud-provider/properties/cloud-config/aadClientId?
  value: ((client_id))

- type: replace
  path: /instance_groups/name=master/jobs/name=cloud-provider/properties/cloud-config/aadClientSecret?
  value: ((client_secret))

- type: replace
  path: /instance_groups/name=worker/jobs/name=cloud-provider/properties/cloud-config/useManagedIdentityExtension
  value: false

- type: replace
  path: /instance_groups/name=worker/jobs/name=cloud-provider/properties/cloud-config/aadClientId?
  value: ((client_id))

- type: replace
  path: /instance_groups/name=worker/jobs/name=cloud-provider/properties/cloud-config/aadClientSecret?
  value: ((client_secret))
