- type: replace
  path: /instance_groups/name=master/jobs/name=cloud-provider/properties/cloud-provider/aws?
  value:
    access_key_id: ((aws_access_key_id_master))
    secret_access_key: ((aws_secret_access_key_master))
