#!/usr/bin/env bash

set -e

kubernetes_version=$1

main() {
  if [ $# -ne 1 ]; then
    echo "Usage: $(basename "$0") [KUBERNETES VERSION]"
    exit  1
  fi

  staging_dir=$(mktemp -d)

  trap '{ cd - ; rm -rf "$staging_dir"; exit 255; }' SIGINT

  binaries=(
    "kube-apiserver"
    "kube-controller-manager"
    "kube-proxy"
    "kube-scheduler"
    "kubectl"
    "kubelet"
  )

  pushd "$(dirname "${BASH_SOURCE[0]}")/.."

    for binary in "${binaries[@]}"; do
      download "${binary}"
      add_blob "${binary}"
    done

  popd
}

download() {
  local binary_name
  binary_name="$1"

  wget -O "${staging_dir}/${binary_name}" "https://storage.googleapis.com/kubernetes-release/release/v${kubernetes_version}/bin/linux/amd64/${binary_name}"
}

add_blob() {
  local binary_name blob_name
  binary_name="$1"
  blob_name=$(bosh-cli blobs | grep "$binary_name" | awk '{ print $1 }')

  bosh-cli remove-blob "$blob_name"
  bosh-cli add-blob "${staging_dir}/${binary_name}" "kubernetes-${kubernetes_version}/$binary_name"
}

main "$@"
