#!/bin/bash
set -e


main() {
    local images staging_dir

    images=(
      "gcr.io/google_containers/pause-amd64:3.0"
      "gcr.io/google_containers/heapster:v1.1.0"
      "kubernetes/heapster_influxdb:v0.6"
      "gcr.io/google_containers/kubedns-amd64:1.7"
      "gcr.io/google_containers/kube-dnsmasq-amd64:1.3"
      "gcr.io/google_containers/exechealthz-amd64:1.1"
      "gcr.io/google_containers/kubernetes-dashboard-amd64:v1.6.0"
    )

    staging_dir=$(mktemp -d)

    trap '{ cd - ; rm -rf "$staging_dir"; exit 255; }' SIGINT

    pushd "$(dirname "${BASH_SOURCE[0]}")/.."
        for image in "${images[@]}"; do
            output_file=$(echo "${image}" | sed 's/\//_/g').tgz
            output_path="${staging_dir}/${output_file}"
            download "${image}" "${output_path}"
            add_blob "${output_path}" "${output_file}"
        done
    popd
}

download() {
    local image_name output_path
    image_name="$1"
    output_path="$2"

    docker pull "${image_name}"
    docker save "${image_name}" | gzip > "${output_path}"

    echo "saving to: ${output_path}"
}

add_blob() {
    local binary_path="$1"
    local binary_name="$2"

    bosh-cli add-blob "${binary_path}" "container-images/${binary_name}"
}

main
