#!/bin/sh

download_image() {
    image_name=$1
    output_name="images/`echo $1 | sed 's/\//_/g'`"

    docker pull ${image_name}    
    docker save ${image_name} | gzip > ${output_name}.tgz
}

mkdir -p images

download_image "gcr.io/google_containers/pause" 
download_image "gcr.io/google_containers/heapster:v1.1.0"
download_image "kubernetes/heapster_influxdb:v0.6"
download_image "gcr.io/google_containers/kubedns-amd64:1.7"
download_image "gcr.io/google_containers/kube-dnsmasq-amd64:1.3"
download_image "gcr.io/google_containers/exechealthz-amd64:1.1"
download_image "gcr.io/google_containers/kubernetes-dashboard-amd64:v1.4.2"
