#!/bin/bash -eu
[ -z ${DEBUG+x} ] || set -x

setup() {
    GOPATH="$( cd "$( dirname "${BASH_SOURCE[0]}" )/../" && pwd )"
}

test_package() {
    local package=${1}
    pushd "${GOPATH}/src/${package}" > /dev/null
        echo "${package}: Installing ginkgo"
        go install ./vendor/github.com/onsi/ginkgo/ginkgo

        echo "${package}: Running go vet"
        go vet $(go list "./..." | grep -v "${package}/vendor/")

        echo "${package}: Running ginkgo"
        ginkgo -p -r .

        echo "${package}: Running ginkgo to check race conditions"
        ginkgo -p -r -race .
    popd > /dev/null
}

setup
test_package "route-sync"
test_package "ensure-specs-running"
