#!/bin/bash -e
[ -z "$DEBUG" ] || set -x

project_root="$( cd "$( dirname "${BASH_SOURCE[0]}" )/../" && pwd )"

test_route_sync() {
  pushd "${project_root}/src/route-sync" > /dev/null
    export GOPATH=${project_root}
    echo "Running go vet"
    go vet $(go list "./..." | grep -v "route-sync/vendor/")
    go vet -shadow $(go list "./..." | grep -v "route-sync/vendor/")
    echo "Running ginkgo"
    ginkgo -r -race .
    echo "Compiling final binary"
    go build
  popd > /dev/null
}

test_release_specs() {
  pushd "${project_root}" > /dev/null
    bundle install
    bundle exec rspec spec/*_spec.rb
    bundle exec rubocop
  popd > /dev/null

}

test_route_sync
test_release_specs

exit 0
