#!/usr/bin/env bash
set -e

main() {
  local staging_dir kubernetes_version
  kubernetes_version=$1

  if [ $# -ne 1 ]; then
    echo "Usage: $(basename "$0") [KUBERNETES VERSION]"
    exit  1
  fi

  staging_dir=$(mktemp -d)

  trap '{ rm -rf "$staging_dir"; }' EXIT

  binaries=(
    "kube-apiserver"
    "kube-controller-manager"
    "kube-proxy"
    "kube-scheduler"
    "kubectl"
    "kubelet"
  )

  pushd "$(dirname "${BASH_SOURCE[0]}")/.."

    for binary in "${binaries[@]}"; do
      download "${binary}" "${staging_dir}" "${kubernetes_version}"
      add_blob "${binary}" "${staging_dir}" "${kubernetes_version}"
    done

  popd
}

download() {
  local binary_name staging_dir kubernetes_version
  binary_name="$1"
  staging_dir="$2"
  kubernetes_version="$3"

  wget -O "${staging_dir}/${binary_name}" "https://storage.googleapis.com/kubernetes-release/release/v${kubernetes_version}/bin/linux/amd64/${binary_name}"
}

add_blob() {
  local binary_name blob_name staging_dir kubernetes_version
  binary_name="$1"
  staging_dir="$2"
  kubernetes_version="$3"
  blob_name=$(bosh blobs --column path | grep "$binary_name" )

  bosh remove-blob "$blob_name"
  bosh add-blob "${staging_dir}/${binary_name}" "kubernetes-${kubernetes_version}/$binary_name"
}

main "$@"
