// This file was generated by counterfeiter
package poolerfakes

import (
	"route-sync/pooler"
	"route-sync/route"
	"sync"
)

type FakePooler struct {
	StartStub        func(route.Source, route.Router) (done chan<- struct{})
	startMutex       sync.RWMutex
	startArgsForCall []struct {
		arg1 route.Source
		arg2 route.Router
	}
	startReturns struct {
		result1 chan<- struct{}
	}
	startReturnsOnCall map[int]struct {
		result1 chan<- struct{}
	}
	RunningStub        func() bool
	runningMutex       sync.RWMutex
	runningArgsForCall []struct{}
	runningReturns     struct {
		result1 bool
	}
	runningReturnsOnCall map[int]struct {
		result1 bool
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakePooler) Start(arg1 route.Source, arg2 route.Router) (done chan<- struct{}) {
	fake.startMutex.Lock()
	ret, specificReturn := fake.startReturnsOnCall[len(fake.startArgsForCall)]
	fake.startArgsForCall = append(fake.startArgsForCall, struct {
		arg1 route.Source
		arg2 route.Router
	}{arg1, arg2})
	fake.recordInvocation("Start", []interface{}{arg1, arg2})
	fake.startMutex.Unlock()
	if fake.StartStub != nil {
		return fake.StartStub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1
	}
	return fake.startReturns.result1
}

func (fake *FakePooler) StartCallCount() int {
	fake.startMutex.RLock()
	defer fake.startMutex.RUnlock()
	return len(fake.startArgsForCall)
}

func (fake *FakePooler) StartArgsForCall(i int) (route.Source, route.Router) {
	fake.startMutex.RLock()
	defer fake.startMutex.RUnlock()
	return fake.startArgsForCall[i].arg1, fake.startArgsForCall[i].arg2
}

func (fake *FakePooler) StartReturns(result1 chan<- struct{}) {
	fake.StartStub = nil
	fake.startReturns = struct {
		result1 chan<- struct{}
	}{result1}
}

func (fake *FakePooler) StartReturnsOnCall(i int, result1 chan<- struct{}) {
	fake.StartStub = nil
	if fake.startReturnsOnCall == nil {
		fake.startReturnsOnCall = make(map[int]struct {
			result1 chan<- struct{}
		})
	}
	fake.startReturnsOnCall[i] = struct {
		result1 chan<- struct{}
	}{result1}
}

func (fake *FakePooler) Running() bool {
	fake.runningMutex.Lock()
	ret, specificReturn := fake.runningReturnsOnCall[len(fake.runningArgsForCall)]
	fake.runningArgsForCall = append(fake.runningArgsForCall, struct{}{})
	fake.recordInvocation("Running", []interface{}{})
	fake.runningMutex.Unlock()
	if fake.RunningStub != nil {
		return fake.RunningStub()
	}
	if specificReturn {
		return ret.result1
	}
	return fake.runningReturns.result1
}

func (fake *FakePooler) RunningCallCount() int {
	fake.runningMutex.RLock()
	defer fake.runningMutex.RUnlock()
	return len(fake.runningArgsForCall)
}

func (fake *FakePooler) RunningReturns(result1 bool) {
	fake.RunningStub = nil
	fake.runningReturns = struct {
		result1 bool
	}{result1}
}

func (fake *FakePooler) RunningReturnsOnCall(i int, result1 bool) {
	fake.RunningStub = nil
	if fake.runningReturnsOnCall == nil {
		fake.runningReturnsOnCall = make(map[int]struct {
			result1 bool
		})
	}
	fake.runningReturnsOnCall[i] = struct {
		result1 bool
	}{result1}
}

func (fake *FakePooler) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.startMutex.RLock()
	defer fake.startMutex.RUnlock()
	fake.runningMutex.RLock()
	defer fake.runningMutex.RUnlock()
	return fake.invocations
}

func (fake *FakePooler) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ pooler.Pooler = new(FakePooler)
