name: build

on:
  push:
    branches: [ gh-actions-build ]

jobs:
  build:
    container: 
      image: gcr.io/cf-pks-golf/pcfkubo/kubo-ci
    runs-on: ubuntu-latest
    steps:
    - name: Checkout kubo-release
      uses: actions/checkout@v2
    - name: Build release
      run: .github/tasks/build.sh
    - id: upload-file
      uses: google-github-actions/upload-cloud-storage@main
      with:
        path: kubo-release-*.tgz
        destination: github-dev-releases