name: build

on:
  push:
    branches: [ gh-actions-build ]

jobs:
  build:
    container: 
      image: gcr.io/cf-pks-golf/pcfkubo/kubo-ci
    runs-on: ubuntu-latest
    steps:
    - name: Checkout kubo-release
      uses: actions/checkout@v2
    - name: Build release
      run: .github/tasks/build.sh
    - id: upload-file
      uses: google-github-actions/upload-cloud-storage@main
      with:
        credentials: ${{ secrets.GCS_SA_CI }}
        path: .
        destination: github-dev-releases
        glob: 'kubo-release-*.tgz'
  test:
    needs: [build]
    container: 
      image: gcr.io/cf-pks-golf/pcfkubo/kubo-ci
    runs-on: ubuntu-latest
    strategy:
      matrix:
        iaas: [gcp]
        testcase: [integration]
    env:
      TESTCASE: ${{ matrix.testcase }}
      IAAS: ${{ matrix.iaas }}
    steps:
      - name: Checkout kubo-release
        uses: actions/checkout@v2
      - name: setup-bosh-variables
        env: 
          SOURCE: ${{ secrets.GCS_SA_CI }}
        run: |
          echo "${SOURCE}" > source
      - name: upload-stemcell
        run: .github/tasks/upload-stemcell.sh
        env:
          SOURCE_FILE: source
      - name: download-dep-releases
        run: yq read manifests/cfcr.yml releases.*.url | grep -v null | grep -v kubo-[0-9] | sed 's|^-\ ||g' | xargs -n 1 curl -SLJO
