name: build

on:
  push:
    branches: [ gh-actions-build ]

jobs:
  build:
    container: 
      image: gcr.io/cf-pks-golf/pcfkubo/kubo-ci
    runs-on: ubuntu-latest
    steps:
    - name: Checkout kubo-release
      uses: actions/checkout@v2
    - name: Build release
      run: .github/tasks/build.sh