name: build

on:
  push:
    branches: [ gh-actions-build ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout kubo-release
      uses: actions/checkout@v2
    - name: Install bosh-cli
      run: brew install cloudfoundry/tap/bosh-cli
    - name: Build release
      run: ./github/tasks/build.sh